name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: docker-build-push
      run: make docker-build docker-push IMG="bpmfio/bpmf-operator:v0.0.1"
